# Generated by Django 5.1.1 on 2024-10-10 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_alter_product_product_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='category_level',
            field=models.IntegerField(blank=True, null=True, verbose_name='დონე'),
        ),
    ]
