# Generated by Django 5.1.1 on 2024-10-12 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_alter_category_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_quantity',
            field=models.IntegerField(blank=True, null=True, verbose_name='მარაგშია:'),
        ),
    ]
