# Generated by Django 5.1.1 on 2024-10-13 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_product_product_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='category_level',
        ),
    ]
